<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>mz.hospital</groupId>
    <artifactId>medisync-corba-server</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jacorb.version>3.9</jacorb.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.jacorb</groupId>
            <artifactId>jacorb</artifactId>
            <version>${jacorb.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jacorb</groupId>
            <artifactId>jacorb-omgapi</artifactId>
            <version>${jacorb.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jboss.spec.javax.rmi</groupId>
            <artifactId>jboss-rmi-api_1.0_spec</artifactId>
            <version>1.0.6.Final</version>
        </dependency>

        <dependency>
            <groupId>org.jacorb</groupId>
            <artifactId>jacorb-services</artifactId>
            <version>${jacorb.version}</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>idlj-maven-plugin</artifactId>
                <version>1.2.1</version>

                <configuration>
                    <compiler>jacorb</compiler>
                    <sourceDirectory>
                        ${project.basedir}/src/main/idl
                    </sourceDirectory>
                </configuration>

                <dependencies>
                    <dependency>
                        <groupId>org.jacorb</groupId>
                        <artifactId>jacorb-idl-compiler</artifactId>
                        <version>${jacorb.version}</version>
                    </dependency>
                </dependencies>

                <executions>
                    <execution>
                        <id>generate-idl</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>

            </plugin>

        </plugins>
    </build>

</project>